### ISSUE TITLE
Looks like INSTANCE_NAME env var doesn't properly handle names with spaces inside

### ISSUE THREAD

**Issue by getkirill** [jordemort/docker-pleroma#34]
this is what logs yields when INSTANCE_NAME is set to `Ploobis Domain Pleroma`:
```
pleroma   | ** (MatchError) no match of right hand side value: {[output: "/etc/pleroma/config.exs", output_psql: "/tmp/setup_db.sql", domain: "pleroma.ploobis.com", instance_name: "Ploobis", admin_email: "no-email-yet@example.com", notify_email: "no-email-yet@example.com", dbhost: "db", dbname: "pleroma", dbuser: "postgres", dbpass: "FuckYOuStopBruteforcingSH1T10234983290480", rum: "n", indexable: "y", db_configurable: "y", uploads_dir: "/var/lib/pleroma/uploads", static_dir: "/var/lib/pleroma/static", listen_ip: "0.0.0.0", listen_port: "4000", strip_uploads: "y", anonymize_uploads: "y", dedupe_uploads: "y"], ["Domain", "Pleroma"], []}
pleroma   |     (pleroma 2.4.3) lib/mix/tasks/pleroma/instance.ex:15: Mix.Tasks.Pleroma.Instance.run/1
pleroma   |     (stdlib 3.12.1.2) erl_eval.erl:680: :erl_eval.do_apply/6
pleroma   |     (elixir 1.10.4) lib/code.ex:341: Code.eval_string_with_error_handling/3
pleroma   | !!! Config path is not declared! Please ensure it exists and that PLEROMA_CONFIG_PATH is unset or points to an existing file
```
Docker Compose file:
```yaml
version: '3.1'

services:

  db:
    image: postgres:12-alpine
    container_name: postgres
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pleroma
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: FuckYOuStopBruteforcingSH1T10234983290480

  app:
    image: jordemort/pleroma:latest
    container_name: pleroma
    restart: unless-stopped
    ports:
      - "4000:4000"
    volumes:
      - ./data/etc/pleroma:/etc/pleroma
      - ./data/uploads:/var/lib/pleroma/uploads
      - ./data/static:/var/lib/pleroma/static
    environment:
      DOMAIN: pleroma.ploobis.com
      INSTANCE_NAME: "Ploobis Domain Pleroma"
      ADMIN_EMAIL: no-email-yet@example.com
      NOTIFY_EMAIL: no-email-yet@example.com
      POSTGRES_HOST: db
      POSTGRES_DB: pleroma
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: FuckYOuStopBruteforcingSH1T10234983290480
```
